// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./protoStringAvg.proto
package info.sodapanda.sodaplayer.socket;

import com.squareup.wire.ByteString;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Label.REPEATED;

public final class strAvg extends Message {

  public static final List<ByteString> DEFAULT_STRS = Collections.emptyList();

  @ProtoField(tag = 1, type = BYTES, label = REPEATED)
  public final List<ByteString> strs;

  private strAvg(Builder builder) {
    super(builder);
    this.strs = immutableCopyOf(builder.strs);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof strAvg)) return false;
    return equals(strs, ((strAvg) other).strs);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = strs != null ? strs.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<strAvg> {

    public List<ByteString> strs;

    public Builder() {
    }

    public Builder(strAvg message) {
      super(message);
      if (message == null) return;
      this.strs = copyOf(message.strs);
    }

    public Builder strs(List<ByteString> strs) {
      this.strs = strs;
      return this;
    }

    @Override
    public strAvg build() {
      return new strAvg(this);
    }
  }
}
